name: Gorkin Bot

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Set a timeout to ensure the job doesn't run indefinitely
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: |
          cd src
          echo 'import os
          import random
          from datetime import datetime
          from dotenv import load_dotenv
          from bot import GorkinBot

          # Initialize bot
          load_dotenv()
          bot = GorkinBot()

          # Post a random thought
          if random.random() < 0.7:  # 70% chance to tweet
              print("Attempting to post a random thought...")
              bot.post_random_thought()

          # Check mentions
          print("Checking for mentions...")
          bot.process_mentions()' > run_once.py
          python run_once.py 